const {
	REACT_APP_BUCKETNAME,
	REACT_APP_REGION,
	REACT_APP_ACCESSKEYID,
	REACT_APP_SECRETACCESSKEY
} = process.env
export const AwsConfig = {
	bucketName: REACT_APP_BUCKETNAME,
	region: REACT_APP_REGION,
	accessKeyId: REACT_APP_ACCESSKEYID,
	secretAccessKey: REACT_APP_SECRETACCESSKEY
}
