export const projectTypes = {
  GET_PROJECTS: 'GET_PROJECTS',
  SELECT_PROJECT: 'SELECT_PROJECT',
  SET_TARGET_ITEM: 'SET_TARGET_ITEM'
}

export const contactTypes = {
  SET_CONTACT: 'SET_CONTACT'
}

export const uiTypes = {
  TOGGLE_POLICY: 'TOGGLE_POLICY',
  TOGGLE_DRAWER: 'TOGGLE_DRAWER',
  TOGGLE_DELETE: 'TOGGLE_DELETE'
}

export const uploadTypes = {
  APPEND_FILE_LIST: 'APPEND_FILE_LIST',
  UPLOAD_CHANGE: 'UPLOAD_CHANGE',
  TOGGLE_EDIT: 'TOGGLE_EDIT',
  PRELOAD_FORM: 'PRELOAD_FORM'
}

export const adminProjectTypes = {
  SELECT_ADMIN_PROJECT: 'SELECT_ADMIN_PROJECT',
  TARGET_ITEM: 'TARGET_ITEM',
  DELETE_PROJECT: 'DELETE_PROJECT',
  GET_DASH_PROJECTS: 'GET_DASHPROJECTS'
}
