export const projectTypes = {
  GET_PROJECTS: 'GET_PROJECTS',
  SELECT_PROJECT: 'SELECT_PROJECT',
  SET_TARGET_ITEM: 'SET_TARGET_ITEM'
}

export const contactTypes = {
  SET_CONTACT: 'SET_CONTACT'
}

export const uiTypes = {
  TOGGLE_POLICY: 'TOGGLE_POLICY',
  TOGGLE_DRAWER: 'TOGGLE_DRAWER',
  TOGGLE_DELETE: 'TOGGLE_DELETE'
}

export const uploadTypes = {
  APPEND_FILE_LIST: 'APPEND_FILE_LIST',
  UPLOAD_CHANGE: 'UPLOAD_CHANGE',
  TOGGLE_EDIT: 'TOGGLE_EDIT',
  PRELOAD_FORM: 'PRELOAD_FORM'
}

export const adminProjectTypes = {
  SELECT_ADMIN_PROJECT: 'SELECT_ADMIN_PROJECT',
  TARGET_ITEM: 'TARGET_ITEM',
  DELETE_PROJECT: 'DELETE_PROJECT',
  GET_DASH_PROJECTS: 'GET_DASHPROJECTS',
  SWAP_UPDATE: 'SWAP_UPDATE',
  APPEND_PROJECT: 'APPEND_PROJECT'
}

export const authTypes = {
  SET_AUTH_FORM: 'SET_AUTH_FORM',
  TOGGLE_AUTHENTICATED: 'TOGGLE_AUTHENTICATED',
  RESET_AUTH: 'RESET_AUTH',
  SET_CURRENT_USER: 'SET_CURRENT_USER'
}

export const messageTypes = {
  GET_MESSAGES: 'GET_MESSAGES',
  SET_MESSAGE_VIEW: 'SET_MESSAGE_VIEW',
  CHANGE_PAGE: 'CHANGE_PAGE',
  CHANGE_LIMIT: 'CHANGE_LIMIT'
}
